#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL SOURCES
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	mkdir -p "$install_dir"
	cp -r ../sources/* "$install_dir"
fi

#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_config_add_nginx

#=================================================
# USE THE CONFIG FILE
#=================================================

# FIXMEhelpers2.1: ynh_replace used with positional args. Please add the keywords: --match=, --replace=, --file=
ynh_replace "(no-config)" "config.json" "$install_dir/index.html"

#=================================================
# COPY THE CONFIG FILE
#=================================================

# Copie ou modification d'un fichier de config
ynh_config_add --template="config.json" --destination="$install_dir/config.json"

#=================================================
# SECURING FILES AND DIRECTORIES
#=================================================

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
